export const PUSH_ROUTE = 'PUSH_ROUTE'
export const POP_ROUTE = 'POP_ROUTE'
export const SEARCH_DONE = 'SEARCH_DONE'
export const UPDATE_CURRENT_ITEM = 'UPDATE_CURRENT_ITEM'
export const UPDATE_MAIN_ITEM = 'UPDATE_MAIN_ITEM'
export const IDLE = 'IDLE'